### PR TITLE
Use correct version in schema

### LINKED ISSUE #57: The generated schema has wrong version number
We need to generate the schema with the correct version number by loading it from `package.json`

https://github.com/platformatic/ai-warp/blob/193fbc781745f52bbec4e43dfa50c73d63c6f3f2/schema.json#L3

### PR DESCRIPTION
**Pull request by flakey5**

### CODE REVIEW

File: lib/schema.ts [hunk 1]
```diff
@@ -309,5 +310,9 @@ const aiWarpSchema = {
 export { aiWarpSchema as schema }
 
 if (process.argv.length > 2 && process.argv[2] === '--dump-schema') {
+  const pkgJson: any = readFileSync('package.json', 'utf8')
+  // @ts-expect-error
+  schema.version = pkgJson.version
```
Comment (mcollina) [inline lib/schema.ts]: This should always be correct, not just when the schema is generated.

File: schema.json [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {
   "$id": "ai-warp",
-  "version": "1.37.1",
+  "version": "1.39.0",
```
Comment (mcollina) [inline schema.json]: Unfortunately this is not correct.

**Review by mcollina — CHANGES_REQUESTED** [review]
can you add a test?

**Review by mcollina — APPROVED** [review]
lgtm
